

CREATE DATABASE desafio;

CREATE SCHEMA desafio;

CREATE TABLE desafio.usuario (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	usuario varchar(255) NULL,
	senha varchar(255) NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

INSERT INTO desafio.usuario (usuario, senha) VALUES('admin', '123456');
INSERT INTO desafio.usuario (usuario, senha) VALUES('comun', '123456');



CREATE TABLE desafio.cliente (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bairro varchar(255) NULL,
	cep varchar(255) NULL,
	cidade varchar(255) NULL,
	complemento varchar(255) NULL,
	cpf varchar(255) NULL,
	logradouro varchar(255) NULL,
	nome varchar(255) NULL,
	uf varchar(255) NULL,
	CONSTRAINT cliente_pkey null
);


CREATE TABLE desafio.email (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255) NULL,
	cliente_id int8 NULL,
	CONSTRAINT email_pkey PRIMARY KEY (id),
	CONSTRAINT fkmv73jqkep03fr08gsysyrdp6u FOREIGN KEY (cliente_id) REFERENCES desafio.cliente(id)
);


CREATE TABLE desafio.telefone (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	telefone varchar(255) NULL,
	tipo varchar(255) NULL,
	cliente_id int8 NULL,
	CONSTRAINT telefone_pkey PRIMARY KEY (id),
	CONSTRAINT fk8aafha0njkoyoe3kvrwsy3g8u FOREIGN KEY (cliente_id) REFERENCES desafio.cliente(id)
);
