/*CREATE DATABASE desafio;

CREATE SCHEMA desafio;*/



CREATE TABLE desafio.usuario (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	usuario varchar(255) NULL,
	senha varchar(255) NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

INSERT INTO desafio.usuario (usuario, senha) VALUES('admin', '123456');
INSERT INTO desafio.usuario (usuario, senha) VALUES('comun', '123456');
